// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBSGl0F484N-M-eH9qu7NERUT7BDFmdY',
    appId: '1:331886771893:web:8f4cfdefba144077e808fc',
    messagingSenderId: '331886771893',
    projectId: 'jhon-seafood-app-9809b',
    authDomain: 'jhon-seafood-app-9809b.firebaseapp.com',
    storageBucket: 'jhon-seafood-app-9809b.firebasestorage.app',
    measurementId: 'G-EPJ982J8K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg902rvqQjo-SMra6JM2xDb6-_Ma1HmYw',
    appId: '1:331886771893:android:eab8c5bc07531df0e808fc',
    messagingSenderId: '331886771893',
    projectId: 'jhon-seafood-app-9809b',
    storageBucket: 'jhon-seafood-app-9809b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbKOddf1d-l6oEi6Sh1fz4iSuVOyP3aQ',
    appId: '1:331886771893:ios:eb0f2e47d9186838e808fc',
    messagingSenderId: '331886771893',
    projectId: 'jhon-seafood-app-9809b',
    storageBucket: 'jhon-seafood-app-9809b.firebasestorage.app',
    iosBundleId: 'com.example.jhonSeafoodApp',
  );
}
